# Override values for Focalboard.

nameOverride: focal

image:
  tag: 0.7.0
  pullPolicy: Always

controller:
  strategy: RollingUpdate

# -- environment variables. See more environment variables in the [image entrypoint script](https://github.com/FlipEnergy/container-images/blob/main/focalboard/entrypoint.sh)
# @default -- See below
env:
  SERVER_ROOT: https://focal.pleasenoddos.com
  DBTYPE: postgres

ingress:
  main:
    enabled: true
    hosts:
      - host: focal.pleasenoddos.com
        paths:
          - path: /

nodeSelector:
  kubernetes.io/arch: amd64
