# Override values for pretend-youre-xyzzy.

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: xyzzy.pleasenoddos.com
      paths:
        - path: /

resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 125Mi

nodeSelector:
  kubernetes.io/arch: amd64
