# Override values for pretend-youre-xyzzy.

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: xyzzy.pleasenoddos.com
      paths:
        - path: /

resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 512Mi

nodeSelector:
  # kubernetes.io/arch: amd64
  kubernetes.io/hostname: k8s-node-1.tgp
