apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  storageClassName: postgresql
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/syncthing-data/postgresql
    server: k8s-node-1.tgp
