# temp job to restart focal to avoid connection issues with PG
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: reset-focal-conns
  namespace: postgresql
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: default
          restartPolicy: Never
          containers:
            - name: psql
              image: bitnami/postgresql
              command:
                - /bin/sh
                - -c
                - -e
                - psql -h postgresql.postgresql -U $POSTGRES_USER -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE usename='focalboard';"
              env:
                - name: POSTGRES_USER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: postgresql-password
                      name: postgresql
