# Override values for owncast.

image:
  tag: 0.0.7
  pullPolicy: Always

strategy:
  type: RollingUpdate

ingress:
  main:
    enabled: true
    hosts:
      - host: stream.pleasenoddos.com
        paths:
          - path: /

# Persistence is required for persistent configuration changes
persistence:
  config:
    enabled: true
    emptyDir:
      enabled: false
    mountPath: /app/data
    storageClass: owncast
    accessMode: ReadWriteOnce
    size: 10Mi

resources:
  limits:
    cpu: '1'
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 125Mi

nodeSelector:
  kubernetes.io/arch: amd64
