# Override values for owncast.

image:
  tag: 0.0.7
  pullPolicy: Always

strategy:
  type: RollingUpdate

service:
  port:
    port: 8080
  additionalServices:
    - enabled: true
      nameSuffix: rtmp
      type: LoadBalancer
      port:
        port: 1935
        name: rtmp
        protocol: TCP
        targetPort: 1935
      externalTrafficPolicy: Local

ingress:
  enabled: true
  hosts:
    - host: stream.pleasenoddos.com
      paths:
        - path: /

# Persistence is required for persistent configuration changes
persistence:
  config:
    enabled: true
    emptyDir:
      enabled: false
    mountPath: /app/data
    storageClass: owncast
    accessMode: ReadWriteOnce
    size: 10Mi

resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector:
  kubernetes.io/arch: amd64
