apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncast
spec:
  storageClassName: owncast
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/owncast-data
    server: k8s-node-1.tgp
