apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
spec:
  storageClassName: prometheus
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/prometheus-data
    server: k8s-nfs-1.tgp
