# Override values for whoogle.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 2

image:
  tag: 0.5.0

strategy:
  type: RollingUpdate

# See more environment variables in the whoogle documentation
# https://github.com/benbusby/whoogle-search#environment-variables
env:
  # WHOOGLE_CONFIG_COUNTRY:
  WHOOGLE_CONFIG_DARK: 1
  # WHOOGLE_CONFIG_SAFE:
  # WHOOGLE_CONFIG_ALTS:
  # WHOOGLE_CONFIG_TOR:
  # WHOOGLE_CONFIG_NEW_TAB:
  # WHOOGLE_CONFIG_GET_ONLY:
  WHOOGLE_CONFIG_URL: https://whoogle.pleasenoddos.com/
  # WHOOGLE_CONFIG_STYLE:
  WHOOGLE_CONFIG_DISABLE: 1

ingress:
  enabled: true
  hosts:
    - host: whoogle.pleasenoddos.com
      paths:
        - path: /

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector:
  kubernetes.io/arch: amd64
