# Default values for bitwarden_rs.

# Set Bitwarden_rs application variables
bitwardenrs:
  # Set Bitwarden URL, mandatory for invitations over email. Recommended if using a reverse proxy / ingress. Format is https://name or http://name
  domain: https://bitwarden.pleasenoddos.com
  # Allow any user to sign-up: https://github.com/dani-garcia/bitwarden_rs/wiki/Disable-registration-of-new-users
  allowSignups: false
  # Show password hints: https://github.com/dani-garcia/bitwarden_rs/wiki/Password-hint-display
  showPasswordHint: true
  # Enable Websockets for notification. https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-WebSocket-notifications
  # Redirect HTTP path "/notifications/hub" to port 3012. Ingress/IngressRoute controllers are automatically configured.
  enableWebsockets: false

service:
  type: LoadBalancer
  httpPort: 80
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.57

persistence:
  enabled: true
  size: 25Mi
  accessMode: ReadWriteOnce
  # Persistent Volume storage class
  storageClass: bitwarden
  ## Use existing Persistent Volume Claim
  # existingClaim:

image:
  pullPolicy: IfNotPresent
  tag: 1.16.3


replicaCount: 1

podSecurityContext:
  fsGroup: 504

securityContext:
  runAsUser: 504
  runAsGroup: 504

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector:
  kubernetes.io/hostname: myserver.tgp
