# Default values for bitwarden_rs.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: 1.18.0

env:
  SIGNUPS_ALLOWED: false
  INVITATIONS_ALLOWED: false
  # SERVER_ADMIN_EMAIL:
  DOMAIN: https://bitwarden.pleasenoddos.com
  # YUBICO_CLIENT_ID
  # YUBICO_SECRET_KEY
  # DATA_FOLDER
  # DATABASE_URL
  # ATTACHMENTS_FOLDER
  # ICON_CACHE_FOLDER
  # ROCKET_LIMITS
  # ROCKET_WORKERS
  # SMTP_HOST
  # SMTP_FROM
  # SMTP_PORT
  # SMTP_SSL
  # SMTP_EXPLICIT_TLS
  # SMTP_USERNAME
  # SMTP_PASSWORD
  SHOW_PASSWORD_HINT: true
  WEB_VAULT_ENABLED: true

service:
  type: LoadBalancer
  httpPort: 80
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.254

ingress:
  enabled: false

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

persistence:
  enabled: true
  size: 25Mi
  accessMode: ReadWriteOnce
  # Persistent Volume storage class
  storageClass: bitwarden
  ## Use existing Persistent Volume Claim
  # existingClaim:
