# Default values for bitwarden-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bitwardenrs/server
  tag: latest
  pullPolicy: IfNotPresent

env:
  SIGNUPS_ALLOWED: false
  INVITATIONS_ALLOWED: true
  # SERVER_ADMIN_EMAIL
  # DOMAIN
  # YUBICO_CLIENT_ID
  # YUBICO_SECRET_KEY
  # DATA_FOLDER
  # DATABASE_URL
  # ATTACHMENTS_FOLDER
  # ICON_CACHE_FOLDER
  # ROCKET_LIMITS
  # ROCKET_WORKERS
  # SMTP_HOST
  # SMTP_FROM
  # SMTP_PORT
  # SMTP_SSL
  # SMTP_EXPLICIT_TLS
  # SMTP_USERNAME
  # SMTP_PASSWORD
  # SHOW_PASSWORD_HINT
  # WEB_VAULT_ENABLED

service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 192.168.1.57

ingress:
  enabled: false

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 50m
   memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

deploymentAnnotations: {}

## Persist data to a persitent volume
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 800Mi
  storageClass: bitwarden
