apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden
spec:
  storageClassName: bitwarden
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/bitwarden
    server: k8s-node-1.tgp
