apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden
  labels:
    type: local
spec:
  storageClassName: bitwarden
  capacity:
    storage: 800Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/bitwarden
