apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden
spec:
  storageClassName: vaultwarden
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/syncthing-data/vaultwarden
    server: k8s-nfs-1
