replicaCount: 1

image:
  repository: omarroth/invidious
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 192.168.1.61

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
   cpu: 50m
   memory: 64Mi

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# See https://github.com/helm/charts/tree/master/stable/postgresql
postgresql:
  initdbScriptsConfigMap: invidious-postgresql-init

  persistence:
    enabled: true
    size: 250Mi
    storageClass: invidious-postgresql

  master:
    nodeSelector:
      kubernetes.io/hostname: myserver.tgp

# https://github.com/iv-org/invidious/wiki/Configuration
config:
  channel_threads: 1
  feed_threads: 1
  db:
    host: invidious-postgresql
    port: 5432
    dbname: invidious
  full_refresh: false
  https_only: false
  domain: invidious.pleasenoddos.com
  captcha_enabled: false
  registration_enabled: false
  default_user_preferences:
    default_home: "Subscriptions"
    feed_menu: ["Subscriptions", "Top", "Trending"]
