# Override values for Hastebin.

nameOverride: haste

image:
  repository: ghcr.io/k8s-at-home/haste-server
  pullPolicy: Always
  tag: latest

controller:
  strategy: RollingUpdate

# See more environment variables in the haste-server documentation
# https://github.com/rwaltr/haste-server
env:
  STORAGE_FILEPATH: "/data"
  STORAGE_TYPE: "file"

ingress:
  main:
    enabled: true
    hosts:
      - host: haste.pleasenoddos.com
        paths:
          - path: /

persistence:
  data:
    enabled: true
    # Persistent Volume Storage Class
    storageClass: haste
    accessMode: ReadWriteOnce
    size: 2Gi
    # Do not delete the pvc upon helm uninstall
    skipuninstall: true
