# Override values for navidrome.

controller:
  replicas: 2
  strategy: RollingUpdate

image:
  tag: 0.44.1
  pullPolicy: Always



env:
  ND_DATAFOLDER: /data
  ND_IMAGECACHESIZE: 512MB
  ND_LOGLEVEL: info
  ND_MUSICFOLDER: /music
  ND_SCANSCHEDULE: "@every 12h0m0s"
  ND_TRANSCODINGCACHESIZE: 512MB
  ND_LASTFM_ENABLED: false
  ND_ENABLESTARRATING: false

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

ingress:
  main:
    enabled: true
    hosts:
      - host: navidrome.pleasenoddos.com
        paths:
          - path: /

resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 250Mi

persistence:
  config:
    enabled: true
    mountPath: /data
    accessMode: ReadWriteOnce
    # Persistent Volume Storage Class
    storageClass: navidrome-data
    size: 1Gi
    # Do not delete the pvc upon helm uninstall
    skipuninstall: true
  music:
    enabled: true
    mountPath: /music
    accessMode: ReadOnlyMany
    # Persistent Volume Storage Class
    storageClass: navidrome-music
    size: 100Gi
    # Do not delete the pvc upon helm uninstall
    skipuninstall: true

nodeSelector:
  kubernetes.io/arch: amd64
