apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-data
spec:
  storageClassName: navidrome-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/syncthing-data/navidrome-data
    server: k8s-node-1.tgp

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music
spec:
  storageClassName: navidrome-music
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/data/syncthing-data/music
    server: k8s-node-1.tgp
