apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: grafana
