datasources:
    datasources.yaml:
        apiVersion: ENC[AES256_GCM,data:sg==,iv:C6F1aVJP706KD03CDpLQ0NS1ijXTk7maZ1/gXK8Ea2Y=,tag:Op2Lt56CKLhZUmUrflYcww==,type:int]
        datasources:
        -   name: ENC[AES256_GCM,data:g2BCBC8o34Pc0/BOZSwowQ==,iv:2MJnZRlfYcGOqQernJUs1ogvZ3AVMeDe8CZL1QX5tQg=,tag:JQgBTP76N1xWsZceWyLVAg==,type:str]
            type: ENC[AES256_GCM,data:B0R7IPCRSZ4=,iv:rE9PxNdw+ubh2kut6xsBN4T4ItNyVhzQJWm1p9aqa/g=,tag:T+2eMD0r8JJtVWqRugwqhA==,type:str]
            url: ENC[AES256_GCM,data:e00XAWKATnPHcnC52eg3NbuQxMqC2Iqaaw==,iv:8UZAg7RuRr6BltGIGIpNRprvZAl2xA/g06qUgTUek+k=,tag:9xIF1mSe+HbFGYfX7WrahA==,type:str]
            access: ENC[AES256_GCM,data:zCzL9v8=,iv:5MMAR7ohRafXktdye9g9nR5ICs36MggKaBrr/pgf6do=,tag:J8I4xyzsqTG96XvDjw/8JA==,type:str]
            isDefault: ENC[AES256_GCM,data:vM+SlQ==,iv:fkC8A2wYdMw2pkxpnnrRTD61h6gD/AeNA6JPTXZUyqw=,tag:xxBTATEq2bwz6aYrsZcTBA==,type:bool]
            database: ENC[AES256_GCM,data:YXFcjjsKUQ==,iv:hHFkDbcddbpIBxoTUpiRb+G5Uf63MqiDCxZ+ci7Q06k=,tag:Md5QiIrbPGKrgKaaXc42bQ==,type:str]
            user: ENC[AES256_GCM,data:eesLNrW1rLIHpg==,iv:NeMTflwlghWndUp1020CrD69Cz5qlMBxYgaoWLx6b1k=,tag:V8i9CpvEU3yTOVx3F8YlaQ==,type:str]
            password: ENC[AES256_GCM,data:fj3SJ3Bykdu9A/8UPw7SjA==,iv:R8jb/2mHG4vl/HeKfvcIP5Fsf6qDqST8AgR1sCwxm4g=,tag:KVxwDym9fogOU83MIhy5EA==,type:str]
            jsonData:
                timeInterval: ENC[AES256_GCM,data:+anZ,iv:lZHSZsgn50FyadRltuKxgwUS9an7nS/B1iLsTHfslxg=,tag:nGu4pWYXvQfDF1pxDrwAUA==,type:str]
        -   name: ENC[AES256_GCM,data:hLuYH5UQjTGlzeuCNEkY05Mq,iv:qJf4mA2+MLnF3Fes/IrKq49iPTd349n2wbgDBTgP2c8=,tag:nf8luOjqtWtIQ2uquB6/ag==,type:str]
            type: ENC[AES256_GCM,data:B0R7IPCRSZ4=,iv:rE9PxNdw+ubh2kut6xsBN4T4ItNyVhzQJWm1p9aqa/g=,tag:T+2eMD0r8JJtVWqRugwqhA==,type:str]
            url: ENC[AES256_GCM,data:e00XAWKATnPHcnC52eg3NbuQxMqC2Iqaaw==,iv:8UZAg7RuRr6BltGIGIpNRprvZAl2xA/g06qUgTUek+k=,tag:9xIF1mSe+HbFGYfX7WrahA==,type:str]
            access: ENC[AES256_GCM,data:zCzL9v8=,iv:5MMAR7ohRafXktdye9g9nR5ICs36MggKaBrr/pgf6do=,tag:J8I4xyzsqTG96XvDjw/8JA==,type:str]
            isDefault: ENC[AES256_GCM,data:IBAgG2I=,iv:G4nu0CnWbo0x+xmpxG4XTBJiJbAWBsHu4fcg+SSq2o0=,tag:D3vHSASrO0Ncme87TZnElg==,type:bool]
            database: ENC[AES256_GCM,data:+pJWIB8ouSSq,iv:leeN/0xeTC+Ou2eUq/ftFxgPStXfNpMhzGazlxNFV5U=,tag:IKNJBW1JOKm2dj1h5uv/5w==,type:str]
            user: ENC[AES256_GCM,data:eesLNrW1rLIHpg==,iv:NeMTflwlghWndUp1020CrD69Cz5qlMBxYgaoWLx6b1k=,tag:V8i9CpvEU3yTOVx3F8YlaQ==,type:str]
            password: ENC[AES256_GCM,data:fj3SJ3Bykdu9A/8UPw7SjA==,iv:R8jb/2mHG4vl/HeKfvcIP5Fsf6qDqST8AgR1sCwxm4g=,tag:KVxwDym9fogOU83MIhy5EA==,type:str]
            jsonData:
                timeInterval: ENC[AES256_GCM,data:MYyR,iv:1EipXj+d8YWrDfeC3sBjWvwRK9JYtVED3s2KjIG6LkE=,tag:9PWwZql43IUU0CUq2pDEUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2020-08-30T19:45:21Z'
    mac: ENC[AES256_GCM,data:OfhOnT20Jyx+Pm23pMVUbeJb7iKkVAjhM35ix4oqpAD9FkzlIeOD02aG3yG7EwVKLExlQWPlph3Uu6OlMr/aQJ96gvuplcxne9OQIM3oLdfWOmq4YnEsxaWLAqI/izS3iXRWYyPBQD8AferGYXh+Vv/BfQKRGu9n3T8r85rS3dc=,iv:KYwxW95OIQoM4Z1KlqGVrag4u04hUdalz57JXMV+eVI=,tag:9bs8K9YDvtGXoHZwk8rphA==,type:str]
    pgp:
    -   created_at: '2020-08-30T18:38:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA6fudZvuRXGvAQv/aH0BCWWsame8reFrF60baupNAHbB10tSDn59Y4P4GKqk
            Uxu7GYKmv/JJV0s2eg7855J/pVhfk0AOLN/0CkzhYjWPXPwk2WcSJj04ULx4dvrL
            B5HPVu965RC2RNFQ5gZMdwBtuoeqq4z2eGOJYv16iokzXTL3lDG5tZXfy1m9AIGI
            3gbzkegn5AwA5+EZIUfZrkrPdE0KTTGdM8NFPAOpNJIf3suhkGp7g6XmRJTOR+nU
            EXOCJoh90a8DiBUaG3Z9f2oFEqbkBn1v6G1nRpHmLA3NNSYLxqUpybO3EEabQBDD
            Opvx8Kr/9lSxFSn2FXQdjRAh0mQc9tts3oQwjdQO5VThCvrCtuZ0uewaMhzMamak
            pPoi5+sn0WwrpBm4f44A/T+39RF+A2/4qG2D1dnLZ/8RfE7BlbRExcvwxuBMWzHz
            CAd++/K9SQy/GaXITBtf5R7OkUrw3eDWumFv1oKasQKx2k6cVz1i8Ng3GocCc6xV
            TICl3N0yNkdRTgmnl8uc0l4BvsI6RfxbKvJQppYybEu1zY9x3Q2mwzGmZidm5mNd
            OO8wDMjxRDLCtB6arHhMHjrrD8f3tZV/ypsudbzDIyLjwr+X/ZLc+orhM8zm+VnP
            Y0O/MiHJF9hdKRwZp9Eh
            =31gD
            -----END PGP MESSAGE-----
        fp: 2D5197D577FE7FBC5F6E95CEE9C5E0078F1F68F0
    unencrypted_suffix: _unencrypted
    version: 3.0.3
