datasources:
    datasources.yaml:
        apiVersion: ENC[AES256_GCM,data:Rw==,iv:V7y2SCT5AMaUwb0tJjSGWZaUYqmQY89flNvYzNVqY24=,tag:UY6MLsjqenEQTkGinpCHRA==,type:int]
        datasources:
        -   name: ENC[AES256_GCM,data:dOrAEa3NINAJUHWjS+sDqQ==,iv:zjLOrkhLj+SekUCps6elrRl3OG0kECc8J42HbHccWJc=,tag:j88RvQ0kEq8H4D5gEY7PNg==,type:str]
            type: ENC[AES256_GCM,data:23GniWdKTPQ=,iv:J3PpV5famvhwe1Eh0XFrslrL3mnx2attkiV1p2tEH6I=,tag:lry3VA7Y6WcAPz5ShwwD6g==,type:str]
            url: ENC[AES256_GCM,data:5+3XZEum7Kheb80mHGvR+rvf9kfa7AXpeA==,iv:c60Yh0OzpCIAuLVjncGLqBMpJZJ7kWHm6NBdUMsnwII=,tag:hnGJ19HY+CN58T3z8R1NNA==,type:str]
            access: ENC[AES256_GCM,data:vRBk9tM=,iv:n7MxCcxyp+zxvuypghyk95mhoK6an/FG3UQxsqiKQ2I=,tag:VU0jJd68s897YZhROKTjCA==,type:str]
            isDefault: ENC[AES256_GCM,data:NSAGXw==,iv:XSMB+QGUNK8tLgwul1KjMBNkyCxBHNz0UgCsF2JvMPE=,tag:z6XEe477yo3efOvJk/O51w==,type:bool]
            database: ENC[AES256_GCM,data:k65gX9peaQ==,iv:rJDd93kLN9ELL8KP6fGZTLYBeOagq9n8+/mQR5bSh9Q=,tag:TmWoxgtP6gmsSv0cZMaNeg==,type:str]
            user: ENC[AES256_GCM,data:74P5kvL3K1bRhw==,iv:ojtMHVuVTS4M0J3eGa98WgNv/xMenFN1BIR64/UVFnM=,tag:vDeJw2Y4k6DhjzmaZnJxvw==,type:str]
            password: ENC[AES256_GCM,data:tE7EXq1ycpNguW07vqMVFQ==,iv:hqr1qwyudFpLaBSJbOLF2JeosLN2eTxc5JiAAIXqMr0=,tag:HILBuJJMHybdSlOB65H3Iw==,type:str]
            jsonData:
                timeInterval: ENC[AES256_GCM,data:T60=,iv:QVW3o6GwcWLTf162oGCUylLnyrLdnt1gpAuVdQf1NOU=,tag:WWuNxRyvCrc3hC2SdYBA6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2020-08-01T22:03:00Z'
    mac: ENC[AES256_GCM,data:AUJGbPWTpwFF2Ut8sZousuWPFWTDOr/ZwOXn1CzrQ2cL+36IFQpngKatMBmLuhRK78v8dxfXQSlSVvxjKy86QU2uSMpS3mrJjxYHslzDlwwV3qLTcksTyrdeDwHJ8ovwUueyyUWzNenkkuWnlXS98cD1NDZ3xBKf8dOCjimvH64=,iv:77YuE0W9gV75P4/UunmUAbC6O7f4sQ1Z77Kj8VQ7LSE=,tag:JH8vMCqHGqgsHTtsDcwh8w==,type:str]
    pgp:
    -   created_at: '2020-07-01T20:34:35Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA6fudZvuRXGvAQv/ZKXfPXZ3hBwFuhKpnILEw2wANzFFeZWC/Tmgb6kLaJGZ
            5iNtqf99wNniJUm5ZBQrmtzhf3a97gJv6vqC1Qkq6BYTcA+vmFmdMAf0IjMMFLbi
            SH1eG5KFcdbRzmoFGrqbJ7/boedG3/SSxdYMPtIg/6q+zHdrzbqm8KdqLNjZm4FV
            DIvq7gqhJ4fPbwzMfxvWNL3CR6hLaXJU5eZhdZVf/+Y2z00NcGRfp9QuzKfNa6JO
            Ru269BoJu6tDM2Wgn11Sk8SPr1go5WkGT84JfnVi2I5gOIROZYO5ypxoZ4ILuRzb
            Vak88wXYtQJ0QwzypsyRZMU+0bCRWtHS0XeKHZFuxztOWdQCQ7Bx0XzZr5m9Br9f
            1uwn+RcBzfgW77pHevtTrq+VZkHhMZKym3huLQwFbe/3x75yFRweCW5drev2heXO
            fMFxBHRC5InTxIylkL89QVqgpM7gXSQ2x97SuxhHKNCS2+mqU4JwvOrDkvH8TpEa
            7vJFpewabVR03objVM+k0l4BhIcKZuAOfDeiM9gPP/XBC8QkWWM1aZtjrffqxM1C
            l805e7LgSCGYRJhJ3gSR0oKErf987H41CkGBjQrXcRqcfVjHLfw6f4XcSOk6OASE
            wy1AAYxjlE8fKbvK3klX
            =D9WX
            -----END PGP MESSAGE-----
        fp: 2D5197D577FE7FBC5F6E95CEE9C5E0078F1F68F0
    unencrypted_suffix: _unencrypted
    version: 3.0.3
