apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud
  labels:
    type: local
spec:
  storageClassName: nextcloud
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nextcloud
