# Default values for fahclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: foldingathome/fah-gpu
  tag: 7.6.13

storageClassName:

# set to some sane defaults to prevent interference
# of your other workload.
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 900m
    memory: 128Mi
