# Default values for fahclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: foldingathome/fah-gpu
  tag: latest
  pullPolicy: Always

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 502
  runAsGroup: 502

storageClassName: folding-at-home

# set to some sane defaults to prevent interference
# of your other workload.
resources:
  limits:
    cpu: 1500m
    memory: 256Mi
  requests:
    cpu: 1400m
    memory: 128Mi
