# Default values for fahclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: foldingathome/fah-gpu
  tag: latest
  pullPolicy: Always

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 502
  runAsGroup: 502

storageClassName:

# set to some sane defaults to prevent interference
# of your other workload.
resources:
  limits:
    cpu: 2000m
    memory: 256Mi
  requests:
    cpu: 1900m
    memory: 128Mi
