apiVersion: v1
kind: PersistentVolume
metadata:
  name: folding-at-home
  labels:
    type: local
spec:
  storageClassName: folding-at-home
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/folding-at-home
