# Configuration for kube ops dashboard values

replicaCount: 1

image:
  repository: hjacobs/kube-ops-view
  tag: latest
  pullPolicy: Always

# Loadbalanced by Metallb
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.51
  externalPort: 80

# Add securityContext
securityContext: {}

# Add securityContext at pod level:
podSecurityContext:
  runAsUser: 1001
  fsGroup: 1001

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi
