# Configuration for kube ops dashboard values

replicaCount: 1

image:
  repository: hjacobs/kube-ops-view
  tag: 20.4.0

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

ingress:
  enabled: true
  path: /
  hostname: kube.pleasenoddos.com

rbac:
  # If true, create & use RBAC resources
  create: true

# Add securityContext at pod level:
podSecurityContext:
  runAsUser: 1001
  fsGroup: 1001

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector:
  kubernetes.io/arch: amd64
