# Configuration for kube ops dashboard values

replicaCount: 1

# Loadbalanced by Metallb
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.51
  externalPort: 80

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi
