# Configuration for kube ops dashboard values

replicaCount: 1

image:
  repository: hjacobs/kube-ops-view
  tag: 20.4.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

ingress:
  enabled: true
  path: /
  hostname: kube.pleasenoddos.com
  annotations: {}
  #   kubernetes.io/ingress.class: nginx

rbac:
  # If true, create & use RBAC resources
  create: true

env:
  QUERY_INTERVAL: 3
  ROUTE_PREFIX: kube.pleasenoddos.com

# Add securityContext at pod level:
podSecurityContext:
  runAsUser: 1001
  fsGroup: 1001

nodeSelector:
  kubernetes.io/arch: amd64
