# Configuration for kube ops dashboard values

replicaCount: 1

# Loadbalanced by Metallb
service:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.51
  externalPort: 80

nodeSelector:
  kubernetes.io/hostname: myserver.tgp
