# Override values for kubeview.

# Kubeview specific, if true the app will function in single namespace mode
# The roles & rolebindings created will be namespaced rather than cluster scoped
limitNamespace: false

loadBalancerIP: 192.168.1.55

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
