apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketchat-mongodb
  labels:
    type: local
spec:
  storageClassName: rocketchat-mongodb
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/rocketchat-mongodb
