apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "statping.fullname" . }}
  labels:
    {{- include "statping.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistenVolume.path }}
