apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "statping.fullname" . }}
  labels:
    {{- include "statping.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: {{ include "statping.fullname" . }}
