# Configuration for OpenVPN

replicaCount: 1

service:
  type: LoadBalancer
  externalPort: 1194
  internalPort: 1194
  loadBalancerIP: 192.168.1.53

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 128Mi

persistence:
  enabled: false

openvpn:
  # Network allocated for openvpn clients (default: 10.240.0.0).
  OVPN_NETWORK: 10.240.0.0
  # Network subnet allocated for openvpn client (default: 255.255.0.0).
  OVPN_SUBNET: 255.255.0.0
  # Protocol used by openvpn tcp or udp (default: udp).
  OVPN_PROTO: tcp
  keystoreSecret: openvpn-keystore-secret
