apiVersion: v1
kind: PersistentVolume
metadata:
  name: sharry
spec:
  storageClassName: sharry
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/sharry-data
    server: k8s-nfs-1
