# Override values for FreshRSS.

image:
  tag: version-1.18.1
  pullPolicy: Always

strategy:
  type: RollingUpdate

ingress:
  main:
    enabled: true
    hosts:
      - host: freshrss.pleasenoddos.com
        paths:
          - path: /


resources:
  limits:
    cpu: 500m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 125Mi

env:
  PUID: 65534 #nobody
  PGID: 65534 #nogroup

persistence:
  config:
    enabled: true
    emptyDir: false
    # Persistent Volume Storage Class
    storageClass: freshrss-data
    size: 1Gi
    # Do not delete the pvc upon helm uninstall
    skipuninstall: true

nodeSelector:
  kubernetes.io/arch: amd64
