# Override values for FreshRSS.

image:
  repository: linuxserver/freshrss
  pullPolicy: IfNotPresent
  tag: version-1.17.0

service:
  port:
    port: 80

ingress:
  enabled: true
  hosts:
    - host: freshrss.pleasenoddos.com
      paths:
        - path: /

resources:
  # limits:
  #   cpu: 100m
  #   memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

env:
  PUID: 65534 #nobody
  PGID: 65534 #nogroup

persistence:
  config:
    enabled: true
    emptyDir: false
    # Persistent Volume Storage Class
    storageClass: freshrss-data
    size: 1Gi
    # Do not delete the pvc upon helm uninstall
    skipuninstall: true

# nodeSelector:
#   k3s.io/hostname: k8s-node-1.tgp
