apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-data
spec:
  storageClassName: freshrss-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/freshrss-data
    server: k8s-nfs-1
