# Default values for wiki.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: requarks/wiki
  pullPolicy: IfNotPresent
  tag: 2.5.191

env:
  # -- mysql, postgres, mariadb, mssql or sqlite
  DB_TYPE: postgres
  # -- Host of the database
  DB_HOST: postgresql.postgresql.svc.cluster.local
  # -- Port of the database
  DB_PORT: 5432

serviceAccount:
  # Specifies whether a service account should be created
  create: false

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- The default port is 3000 used by wiki.ks
  port:
    port: 3000

ingress:
  enabled: true
  hosts:
    - host: wiki.pleasenoddos.com
      paths:
        - path: /

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
  # kubernetes.io/hostname: k8s-node-1.tgp

tolerations: []

affinity: {}
