apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing
spec:
  storageClassName: syncthing
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/syncthing-data
    server: k8s-nfs-1
