# Override values for syncthing.

image:
  tag: 1.16.1
  pullPolicy: Always

service:
  port:
    port: 8384
  additionalServices:
  - enabled: true
    nameSuffix: listen
    type: LoadBalancer
    port:
      port: 22000
      name: listen
      protocol: TCP
      targetPort: 22000
    externalTrafficPolicy: Local
  - enabled: true
    nameSuffix: discovery
    type: LoadBalancer
    port:
      port: 21027
      name: discovery
      protocol: UDP
      targetPort: 21027
    externalTrafficPolicy: Local

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

ingress:
  enabled: true
  hosts:
  - host: syncthing.tgp
    paths:
      - path: /

persistence:
  data:
    enabled: true
    emptyDir:
      enabled: false
    mountPath: /var/syncthing
    storageClass: syncthing
    accessMode: ReadWriteOnce
    size: 500Gi
