# Override values for syncthing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

persistence:
  volume:
    enabled: true
    path: /mnt/data/syncthing-data
    server: k8s-node-1.tgp
    size: 500Gi
  volumeClaim:
    enabled: true
    size: 500Gi

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

service:
  website:
    type: ClusterIP
    port: 80
  backend:
    type: NodePort

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: syncthing.tgp
      paths:
        - path: /

resources:
  # limits:
  #   cpu: 100m
  #   memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  k3s.io/hostname: k8s-node-1.tgp
