# Override values for syncthing.

image:
  tag: 1.17.0
  pullPolicy: Always

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

ingress:
  main:
    enabled: true
    hosts:
    - host: syncthing.tgp
      paths:
        - path: /

persistence:
  data:
    enabled: true
    emptyDir:
      enabled: false
    mountPath: /var/syncthing
    storageClass: syncthing
    accessMode: ReadWriteOnce
    size: 500Gi
