# Override values for syncthing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

persistenVolume:
  path: /mnt/data/syncthing-data
  server: k8s-node-1.tgp

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

service:
  website:
    type: LoadBalancer
    port: 80
    loadBalancerIP: 192.168.1.55
  backend:
    type: NodePort

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
