apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "airsonic.fullname" . }}
  labels:
    {{- include "airsonic.labels" . | nindent 4 }}
data:
  AIRSONIC_PORT: {{ .Values.service.targetPort | quote }}
