apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
  labels:
    type: local
spec:
  storageClassName: influxdb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/influxdb
