apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  storageClassName: influxdb
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/influxdb
    server: k8s-nfs-1.tgp
