apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: influxdb
