apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard
  labels:
    type: local
spec:
  storageClassName: wireguard
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/wireguard
