# wg-access-server config

# Note: on your phone, to allow chromecast to work and allow access to your local network,
#   in the peer section, add your subnet to the front and check Exclude private IPs.

config:
  wireguard:
    externalHost: pleasenoddos.com
  vpn:
    cidr: "10.44.0.0/24"
  dns:
    enabled: true
    upstream:
      - 192.168.1.11

web:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.58

wireguard:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.59

persistence:
  enabled: true
  storageClass: "wireguard"
  size: 25Mi

image:
  repository: place1/wg-access-server
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  kubernetes.io/hostname: myserver.tgp
