# wg-access-server config
config:
  wireguard:
    externalHost: "pleasenoddos.com"

web:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.58

wireguard:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.59

persistence:
  enabled: true
  # Persistent Volume Storage Class
  # If defined, storageClassName: <storageClass>
  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined (the default) or set to null, no storageClassName spec is
  #   set, choosing the default provisioner.  (gp2 on AWS, standard on
  #   GKE, AWS & OpenStack)
  #
  storageClass: "wireguard"
  size: 100Mi

image:
  repository: place1/wg-access-server
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
