# wg-access-server config

# Note: on your phone, to allow chromecast to work and allow access to your local network,
#   in the peer section, add your subnet to the front and check Exclude private IPs.

config:
  wireguard:
    externalHost: pleasenoddos.com
  vpn:
    cidr: "10.44.0.0/24"
  dns:
    enabled: true
    upstream:
      - 192.168.1.11

web:
  service:
    type: ClusterIP

wireguard:
  service:
    type: LoadBalancer

persistence:
  enabled: true
  storageClass: "wireguard"
  size: 25Mi

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - wireguard.tgp
  tls: []

image:
  repository: place1/wg-access-server
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}
