apiVersion: v1
kind: PersistentVolume
metadata:
  name: gonic-data
spec:
  storageClassName: gonic-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/syncthing-data/gonic-data
    server: k8s-nfs-1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gonic-music
spec:
  storageClassName: gonic-music
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/data/syncthing-data/music
    server: k8s-nfs-1
